# PCA

In [15]:
import numpy as np
from sklearn.decomposition import PCA
X = np.array([[-1, -1, 2], [-2, -1, 5], [-3, -2, 12], [1, 1, 2], [2, 1, 4], [3, 2, 15]])

pca = PCA(n_components=3)
X2D = pca.fit_transform(X)
X2D

array([[-4.75933988,  1.02305787, -0.28251414],
       [-1.83072559,  2.08842952,  0.25432992],
       [ 5.04254866,  4.00172609, -0.05775542],
       [-4.54675143, -1.73524883,  0.3061711 ],
       [-2.48995966, -2.41908961, -0.24334634],
       [ 8.5842279 , -2.95887505,  0.02311487]])

In [9]:
pca.explained_variance_ratio_

array([0.99244289, 0.00755711])

In [16]:
import numpy as np
from sklearn.decomposition import PCA
X = np.array([[-1, -1, 2], [-2, -1, 5], [-3, -2, 12], [1, 1, 2], [2, 1, 4], [3, 2, 15]])

pca = PCA()
pca.fit(X)
cumsum =  np.cumsum(pca.explained_variance_ratio_)
d=np.argmax(cumsum >= 0.95)+1
d

2

In [21]:
from sklearn.decomposition import KernelPCA

rbf_pca = KernelPCA(n_components=2, kernel='rbf', gamma=0.04)
X_reduce = rbf_pca.fit_transform(X)
X_reduce

array([[-0.40151273, -0.03085225],
       [-0.20330168, -0.2283189 ],
       [ 0.69752591, -0.64544372],
       [-0.45713625,  0.12405342],
       [-0.38837731,  0.12223356],
       [ 0.75280206,  0.65832789]])

# 调整超参数

In [48]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn import datasets

iris = datasets.load_iris()
X=iris["data"][:,(1,2,3)]
y=(iris["target"] == 2).astype(np.float)

clf = Pipeline([("kpca", KernelPCA(n_components=2)),("log_reg", LogisticRegression())])
param_grid = [{"kpca__gamma":np.linspace(0.03,0.05,10), "kpca__kernel":["rbf","sigmoid"]}]

grid_search = GridSearchCV(clf, param_grid, cv=3)
grid_search.fit(X, y)
grid_search.best_params_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence t

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence t

{'kpca__gamma': 0.04555555555555556, 'kpca__kernel': 'rbf'}